# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
        cuda-version: [12.5.0, 12.4.1, 12.3.2, 12,1.0, 11.8.0]

    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
          cuda: ${{ matrix.cuda-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
