# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        os:
            # - ubuntu-latest
            - windows-latest
        python-version:
            - 3.11
        cuda-version:
            - 12.1.0

    runs-on: ${{ matrix.os }}


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
          cuda: ${{ matrix.cuda-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
